# Generated by Django 5.1.6 on 2026-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='obsidian_path',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
